[package]
name = "model"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools.workspace = true
rayon.workspace = true
anyhow.workspace = true
derive_deref.workspace = true
regex.workspace = true
pathdiff.workspace = true
parsing.workspace = true
tree-sitter.workspace = true
