name: Format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt
        override: true
        rustflags: ""
    - name: Rustfmt Check
      run: |
        if cargo fmt --all -- --check; then
          echo "All files are formatted correctly."
        else
          echo "Formatting issues found. Run 'cargo fmt --all' to fix."
          exit 1
        fi
