name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt
        override: true
        rustflags: ""
    - name: Rustfmt Check
      uses: actions-rust-lang/rustfmt@v1
    - name: Build
      run: cargo build --verbose --locked
    - name: Run tests
      run: cargo test --verbose
